#include "main.h"

#if S_SPLINT_S
    extern ssize_t getline(/*@out@*/ char **restrict lineptr
        , size_t *restrict n, FILE *restrict stream);
#endif

int init_campaign(/*@out@*/ struct campaign *target)
    // initializes a campaign
    // ----- returns -----
    // 0: normal
    // -1: error
{
    // ----- checks
    check(target != NULL, "target was NULL (should be campaign to"
        " initialize).");

    // ----- zero out the entire campaign
        // (needed for no valgrind errors)
    (void) memset(target, 0, sizeof(*target));
    // ----- init
    int foutput = 0;

    // ----- set/initialize all values to their defaults
    (void) memset(target->name, 0, sizeof(target->name));

    foutput = init_grid(&target->encounter_grid);
    check(foutput == 0, "init_grid failed with code %d", foutput);

    foutput = init_note(&target->note);
    check(foutput == 0, "init_note failed with code %d", foutput);

    target->material_list_len = ARRAY_LEN(target->material_list);
    target->creature_list_len = ARRAY_LEN(target->creature_list);

    for (int i = 0; i < MAX_SAVED_CREATURES; i++) {
        target->creature_list[i].name_len
            = ARRAY_LEN(target->creature_list[i].name);
    }

    // NOTE: add this when len values are added to materials
    //for (int i = 0; i < MAX_SAVED_MATERIALS; i++) {
    //}
    return 0;

error:
    return -1;
}

void debug_campaign(struct campaign *target, FILE *format)
// TODO: implement {} and tabs by passing a var for the number of tabs
    //to print
{
    fprintf(format, "CAMPAIGN | ");
    if (target == NULL) {
        fprintf(format, "<NULL>\n");
    } else {
        fprintf(format, "name: '%s' | creature_list_len: %d"
            " | material_list_len: %d | note: ", target->name
            , target->creature_list_len, target->material_list_len);
        print_note(&target->note, format);
        
        (void) fprintf(format, "\n");

        debug_grid(&target->encounter_grid, 1, format);
            // print 1 tab for grid

        (void) fprintf(format, "\n");
        for (int i = 0; i < target->material_list_len; i++) {
            debug_material(&target->material_list[i], 1, format);
        }

        (void) fprintf(format, "\n");

        for (int i = 0; i < target->creature_list_len; i++) {
            debug_creature(&target->creature_list[i], 1, format);
        }
    }
}

static void save_square_ptrs(struct square *target_square
    , struct campaign *target_campaign
    , FILE *restrict material_file
    , FILE *restrict creature_file)
{
    bool is_material_printed = false;
    bool is_creature_printed = false;

    // ----- print the index of the material in the material_list
        // into the material file
    if (target_square->material == NULL) {
        fprintf(material_file, "-1\n");
        is_material_printed = true;
    }
    for (int i = 0; i < target_campaign->material_list_len; i++) {
        if (&target_campaign->material_list[i]
            == target_square->material) {
            fprintf(material_file, "%d\n", i);
            is_material_printed = true;
            break;
        }
    }

    if (!is_material_printed) {
        fprintf(material_file, "-2\n");
    }

    // ----- go through every creature in the square
        // and search for it in the creature_list
    for (int i = 0; i < target_square->max_creatures; i++) {
        is_creature_printed = false;
        if (target_square->creatures[i] == NULL) {
            fprintf(creature_file, "-1\n");
            continue;
        }

        for (int j = 0; j < target_campaign->creature_list_len; j++) {
            if (&target_campaign->creature_list[j]
                == target_square->creatures[i]) {
                // only print the index to file
                fprintf(creature_file, "%d\n", i);
                is_creature_printed = true;
                break;
            }
        }

        if (!is_creature_printed) {
            fprintf(creature_file, "-2\n");
        }
    }
    fprintf(creature_file, "\n");
}

void save_grid_ptrs(struct campaign *target_campaign
    , FILE *restrict material_file
    , FILE *restrict creature_file)
    // saves the material and creatures on a grid by saving its
    // index into a file
{
    struct grid *target_grid = &target_campaign->encounter_grid;
    for (int i = 0; i < target_grid->max_y; i++) {
        for (int j = 0; j < target_grid->max_x; j++) {
            // squares[i][j]
            save_square_ptrs(&target_grid->squares[i][j]
                , target_campaign, material_file, creature_file);
        }
    }
}

void load_grid_material_ptrs(struct campaign *target_campaign
    , FILE *restrict material_file)
    // loads the material and creature values for a grid
    // with updated pointers rather than the old ones

    // ZERO checks for a valid save: this must use a file
    // that was directly generated by save_grid_ptrs
    // TODO include characters
{
    struct grid *target_grid = &target_campaign->encounter_grid;
    char *char_buffer;
    size_t char_buffer_len = 10; // an initial size
    ssize_t nread = -1;
    long index_val = -1;
    int i = 0;
    int j = 0;

    // ----- init char_buffer
    char_buffer = calloc(char_buffer_len, sizeof(char));
    if (char_buffer == NULL)
        return;

    char_buffer = memset(char_buffer, 0, sizeof(char_buffer));

    // ----- read from file
    while (true) {
        // ----- read a line from the file
        nread = getline(&char_buffer, &char_buffer_len, material_file);
        //printf("nread is %d\n", nread);

        // ----- break out of reading when EOF found
        if (nread == -1)
            break;


        // --- get index
        index_val = strtol(char_buffer, NULL, 10);

        // --- set the material
        if (index_val == -1) {
            target_grid->squares[i][j].material = NULL;
            printf("setting [%d][%d] to NULL\n", i, j);
        } else {
            target_grid->squares[i][j].material
                = &target_campaign->material_list[index_val];
            printf("setting [%d][%d] to %p\n", i, j
                , &target_campaign->material_list[index_val]);
        }
        j++;

        // --- check when to move to the next array
            // (j is past len(squares[0]))
        if (j == target_grid->max_x) {
            i++;
            j = 0;
        }
    }

    free(char_buffer);
}
